### ISSUE TITLE
On Macs, library path ends up being wrong, so installation fails

### ISSUE THREAD

**Issue by alexholcombe** [alexander-pastukhov/eyelinkReader#2]
While the normal installation procedure worked a year or two ago on Macs, something broke it, perhaps an OS upgrade or Apple Silicon change.
Now when I try installation on multiple Macs here, which give the following error during the attempt to use edfapi during installation:

```

"tried: '/Library/Frameworks/edfapi.framework/edfapi.framework/Versions/A/edfapi' (no such file)"

```

Please note the redundant "edfapi.framework/edfapi.framework/".  If one of those were deleted, it would find the file.

I worked out a fix for this.  The zzz.R file that sets up the paths has this , specifically for Darwin, on line 70 :

```

library_path <-'/Library/Frameworks/edfapi.framework/'

```

Somewhere else that I haven't worked out, another `edfapi.framework` gets appended to that library_path.
If one simply deletes that `edfapi.framework\` from line 70, everything works (except I get a really weird error where it says .rdb is corrupt in RStudio, whereas everything works in R.app, until I uninstall R and re-install it).

I'll do a bit more testing to ensure this works on our other Mac and then perhaps I should make the edit and set it as a pull request? Ideally to maintain possible backward compatibility, we would just add the version without `edfapi.framework\` as a second directory that it also tries, but unfortunately I don't understand the system well enough to do that.

**Comment by lyuhailong** [comment]
# Here is the solution
System：MacOS 14.6.1 (23G93)  Apple M1 Pro

Environment：Rstudio 

Eyelink SDK:  EyeLink Developers Kit v2.1.762 (macOS 10.12 and up; Intel & M-Series

Run：

```r
install.packages("eyelinkReader")
library(eyelinkReader)
```

Errors:

```r

using C++ compiler: ‘Apple clang version 15.0.0 (clang-1500.3.9.4)’
using SDK: ‘MacOSX14.4.sdk’
clang++ -arch arm64 -std=gnu++17 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I"/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/RcppProgress/include" -I"/private/var/folders/rc/pgy2193j4nj0tvhvw1vdz7q40000gn/T/RtmpPNfOPZ" -I/opt/R/arm64/include   -I"/Library/Frameworks/edfapi.framework/Headers/" -fPIC  -falign-functions=64 -Wall -g -O2   -c edf_interface.cpp -o edf_interface.o
edf_interface.cpp:199:16: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    ::Rf_error(error_message_stream.str().c_str());
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
edf_interface.cpp:199:16: note: treat the string as an argument to avoid this
    ::Rf_error(error_message_stream.str().c_str());
               ^
               "%s", 
edf_interface.cpp:228:16: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    ::Rf_error(error_message_stream.str().c_str());
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
edf_interface.cpp:228:16: note: treat the string as an argument to avoid this
    ::Rf_error(error_message_stream.str().c_str());
               ^
               "%s", 
edf_interface.cpp:276:16: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    ::Rf_error(error_message_stream.str().c_str());
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
edf_interface.cpp:276:16: note: treat the string as an argument to avoid this
    ::Rf_error(error_message_stream.str().c_str());
               ^
               "%s", 
edf_interface.cpp:321:16: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    ::Rf_error(error_message_stream.str().c_str());
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
edf_interface.cpp:321:16: note: treat the string as an argument to avoid this
    ::Rf_error(error_message_stream.str().c_str());
               ^
               "%s", 
4 warnings generated.
clang++ -arch arm64 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o sourceCpp_2.so edf_interface.o -framework edfapi -F/Library/Frameworks/edfapi.framework/ -rpath /Library/Frameworks/edfapi.framework/ -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundationError in dyn.load("/private/var/folders/rc/pgy2193j4nj0tvhvw1vdz7q40000gn/T/RtmpPNfOPZ/sourceCpp-aarch64-apple-darwin20-1.0.13/sourcecpp_17b66ea3df77/sourceCpp_2.so") : 
  unable to load shared object '/private/var/folders/rc/pgy2193j4nj0tvhvw1vdz7q40000gn/T/RtmpPNfOPZ/sourceCpp-aarch64-apple-darwin20-1.0.13/sourcecpp_17b66ea3df77/sourceCpp_2.so':
  dlopen(/private/var/folders/rc/pgy2193j4nj0tvhvw1vdz7q40000gn/T/RtmpPNfOPZ/sourceCpp-aarch64-apple-darwin20-1.0.13/sourcecpp_17b66ea3df77/sourceCpp_2.so, 0x0006): Library not loaded: @rpath/edfapi.framework/Versions/A/edfapi
  Referenced from: <0F38A745-7FCB-3EE6-85BA-BE0FDC4D49DD> /private/var/folders/rc/pgy2193j4nj0tvhvw1vdz7q40000gn/T/RtmpPNfOPZ/sourceCpp-aarch64-apple-darwin20-1.0.13/sourcecpp_17b66ea3df77/sourceCpp_2.so
  Reason: tried: '/Library/Frameworks/edfapi.framework/edfapi.framework/Versions/A/edfapi' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/edfapi.framework/edfapi.framework/Versions/A/edfapi' (no such file), '/Library/Frameworks/edfapi.framework/edfapi.framework/Versions/A/edfapi' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/edfapi.fra
Error: package or namespace load failed for ‘eyelinkReader’ in namespaceExport(ns, exports):
 undefined exports: compiled_library_status, read_edf_file, read_preamble_str

```

**Consult ChatGPT to solve the error process::**

I understand that you're still encountering issues loading the `eyelinkReader` package even after following the previous steps. Thank you for providing the detailed error messages—they are crucial for diagnosing the problem.

### **Analyzing the Error Message**

Let's break down the error message you've provided:

1. **Compiler Warnings**:
    - The warnings about the format string in `edf_interface.cpp` are not critical. They can be addressed later but are unlikely to be causing the immediate problem.
2. **Linker Command**:
    
    The linker command used is:
    
    ```bash
    clang++ -arch arm64 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o sourceCpp_2.so edf_interface.o -framework edfapi -F/Library/Frameworks/edfapi.framework/ -rpath /Library/Frameworks/edfapi.framework/ -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
    
    ```
    
3. **Dynamic Loading Error**:
    
    The critical error is:
    
    ```
    Error in dyn.load("/path/to/sourceCpp_2.so") :
      unable to load shared object '/path/to/sourceCpp_2.so':
      dlopen(/path/to/sourceCpp_2.so, 0x0006): Library not loaded: @rpath/edfapi.framework/Versions/A/edfapi
      Referenced from: /path/to/sourceCpp_2.so
      Reason: tried: '/Library/Frameworks/edfapi.framework/edfapi.framework/Versions/A/edfapi' (no such file), ...
    
    ```
    
    **Key Point**: The system is trying to find the library at:
    
    ```
    /Library/Frameworks/edfapi.framework/edfapi.framework/Versions/A/edfapi
    
    ```
    
    Notice the duplicate `edfapi.framework/edfapi.framework` in the path. This indicates that there's an incorrect path being set somewhere during the build process.
    

### **Identifying the Problem**

The issue seems to be with the **framework search paths** and the **linker flags** used during compilation and linking. Specifically:

- The `F` flag (framework search path) is being set incorrectly to include the framework itself, leading to a duplicate in the path.
- This causes the dynamic linker to look for the framework inside itself, which obviously fails.

### **Solution Steps**

### **1. Correct the Framework Search Path  [here is why the error shows]**

The `-F` flag should point to the directory **containing** the framework, not the framework itself.

- **Incorrect**:
    
    ```
    -F/Library/Frameworks/edfapi.framework/
    
    ```
    
- **Correct**:
    
    ```
    -F/Library/Frameworks/
    
    ```
    

### **2. Modify the Compilation Flags**

We need to adjust the compilation and linking flags used when building the `eyelinkReader` package to ensure that the framework search paths are set correctly. 

[keep reading]

### …

I understand that you're unable to find the `src` directory or the `Makevars` file in your installed `eyelinkReader` package, and the `Makevars` file in the GitHub repository is empty. This makes it challenging to modify the compilation flags as previously suggested.

Let me guide you through an alternative approach to resolve the issue by installing the package from source and manually specifying the necessary compilation flags.

### **Understanding the Situation**

- **Binary vs. Source Installation**: When you install a package using `install.packages()` in R, it often installs a pre-compiled binary version. This binary doesn't include the `src` directory or the `Makevars` file because the package has already been compiled.
- **Need for Source Installation**: To modify the compilation and linking flags (such as correcting the framework search paths), you need to install the package from source. This allows you to adjust the build process.

### **Step-by-Step Solution**

### **1. Install Necessary Tools**

- **Ensure Xcode Command Line Tools Are Installed**:
    
    Open Terminal and run:
    
    ```bash
    xcode-select --install
    
    ```
    
    This installs the necessary compilers and build tools.
    
- **Remove `eyelinkReader` from R. Install the `devtools` Package in R**:
    
    ```
    remove.packages("eyelinkReader")
    install.packages("devtools")
    library(devtools)
    
    ```
    

### **2. Download the Package Source**

- 
- **Option B: Clone from GitHub**
    
    If you prefer the development version:
    
    ```bash
    git clone <https://github.com/alexander-pastukhov/eyelinkReader.git>
    
    ```
    
    This will create an `eyelinkReader` directory in your current path.
    

### **3. Modify the `Makevars` File**

- **Navigate to the `src` Directory**:
    
    ```bash
    cd eyelinkReader/src
    
    ```
    
- **Create or Edit the `Makevars` File**:
    
    If it doesn't exist or is empty, create or open it with a text editor:
    
    ```bash
    nano Makevars
    
    ```
    
- **Add the Correct Compilation Flags**:
    
    Insert the following lines:
    
    ```
    PKG_CPPFLAGS = -I"/Library/Frameworks/edfapi.framework/Headers/"
    PKG_LIBS = -framework edfapi -F/Library/Frameworks/ -rpath /Library/Frameworks/
    
    ```
    
    **Explanation**:
    
    - **`PKG_CPPFLAGS`** specifies the path to the header files.
    - **`PKG_LIBS`** tells the linker where to find the `edfapi` framework.
- **Save and Close the File**:
    
    Press `Ctrl + O` to save and `Ctrl + X` to exit in `nano`.
    

### **4.**

### **5. Install the Package from Source**

- **In R, Install the Package**:
    
    ```
    install.packages("path/to/eyelinkReader", repos = NULL, type = "source")
    
    ```
    
    Replace `path/to/eyelinkReader` with the actual path to the package directory.
    
- **Alternatively, Use `devtools`**:
    
    ```
    library(devtools)
    install_local("path/to/eyelinkReader")
    
    ```
    

### **6. Set Environment Variables**

- **Set the `DYLD_FRAMEWORK_PATH`**:
    
    In your Terminal:
    
    ```bash
    export DYLD_FRAMEWORK_PATH=/Library/Frameworks/
    
    ```
    
    **Note**: Due to macOS System Integrity Protection (SIP), `DYLD_*` variables may not always be respected. Since we're specifying the paths in `Makevars`, this step might not be necessary but can help in some cases.
    
- **Make It Permanent**:
    
    Add the export line to your shell profile (e.g., `~/.zshrc`):
    
    ```bash
    echo 'export DYLD_FRAMEWORK_PATH=/Library/Frameworks/' >> ~/.zshrc
    
    ```
    

### **7. Restart R and Test the Package**

- **Restart RStudio or R Console** to ensure changes take effect.
- **Load the Package**:
    
    ```
    library(eyelinkReader)
    
    ```
    
- **Test a Function**:
    
    ```
    result <- read_edf("path/to/your_data.edf")
    
    ```
    
    Replace `"path/to/your_data.edf"` with the actual path to your EDF file.
    

### **8. It works!!!**

### 

### 

###

**Comment by alexander-pastukhov** [comment]
@alexholcombe @lyuhailong I am terribly sorry for disappearing for some time. Could you test the github version? Does it work now?

**Comment by lyuhailong** [comment]
I didn't directly test the existing GitHub version. However, I downloaded the GitHub version to my local machine as described above, modified the Makevars file, specified the paths for PKG_CPPFLAGS and PKG_LIBS, and then installed eyelinkReader locally. This approach worked successfully. The package is indeed very useful and impressive.

**Comment by alexander-pastukhov** [comment]
@lyuhailong  could you please try installing from Github, so I can confirm that the current version works?
```
library("devtools")
install_github("alexander-pastukhov/eyelinkReader", dependencies=TRUE)
```

**Comment by alexholcombe** [comment]
thanks Sasha and Lyuhailong, I can't risk breaking my current setup at the moment (I've been using eyelinkReader a lot!) :) ), but I'll try to test this on another computer in the next couple days!

**Comment by imanel04** [comment]
hi, i'm also working in @alexholcombe 's  lab and just wanted to confirm that _eyelinkReader_ works on my MacOS 14.3.1 with the R 4.4.1 version. thanks :) !

**Comment by alexander-pastukhov** [comment]
@imanel04 @alexholcombe @lyuhailong When let us consider the issue being closed and I'll submit the updated version to CRAN.
